#!/usr/bin/env ruby
# Set up gems listed in the Gemfile.
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../Gemfile', File.dirname(__FILE__))

require 'rubygems'
require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])
require 'daemons'

options = {
  :app_name   => 'alondra',
  :dir_mode   => :script,
  :dir        => 'tmp/pids'
}

Daemons.run_proc 'alondra', options do

  ENV["ALONDRA_SERVER"] = 'true'
  
  require_relative File.join('..', 'config', 'environment')
  
  log_path = File.expand_path(File.join(File.dirname(__FILE__), '..', 'log', 'alondra.log'))
  
  Rails.logger =  ActiveSupport::BufferedLogger.new(log_path)

  Rails.logger.info "Started alondra server on port #{Alondra::Alondra.config.port}... #{EM.reactor_running?}"

  EM.reactor_thread.join
  
  Rails.logger.info 'Alondra server terminated'
end